### ISSUE TITLE
Duplicate resource tags

### ISSUE THREAD

**Issue by beekhof** [stolostron/hypershift-deployment-controller#167]
The following code needs to check if the tag already exists before appending it.
https://github.com/stolostron/hypershift-deployment-controller/blob/359179cd6b6e60d4999a9b0026f7ad6ecc39c925/pkg/controllers/default_resources.go#L186-L191

Otherwise you can end up with:

```
       resourceTags:
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
            value: owned
          - key: kubernetes.io/cluster/demo-demo-bobbycar-7lpkm-crhfx
```
