### ISSUE TITLE
Should ensure the spec.targetNamespace exists

### ISSUE THREAD

**Issue by zhujian7** [stolostron/hypershift-deployment-controller#30]
Should ensure the spec.targetNamespace exists, or will get the failure:
```
    - conditions:
      - lastTransitionTime: "2022-03-04T06:03:01Z"
        message: 'Failed to apply manifest: namespaces "clusters" not found'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      - lastTransitionTime: "2022-03-04T06:03:01Z"
        message: Resource is not available
        reason: ResourceNotAvailable
        status: "False"
        type: Available
      resourceMeta:
        group: hypershift.openshift.io
        kind: HostedCluster
        name: hypershift-demo
        namespace: clusters
        ordinal: 0
        resource: hostedclusters
        version: v1alpha1
```

Two options:
1. the controller to ensure: add the namespace to the manifestwork, and set the `SelectivelyOrphan` deleteOption to prevent the ns from being deleted if it is created by users.
2. users to ensure: we need to doc this.
